name: Build README

on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: franzdiebold/github-env-vars-action@v1.0.0
      # https://github.com/marketplace/actions/github-environment-variables-action
    - name: Use Node.js
      uses: actions/setup-node@v1
    - run: npm ci
    - run: npm run updateReadme --if-present
      env:
          ENV_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}